export const PRELOAD_API_DOMAIN_TARGET = 'window.helm.<domain>';

export const PRELOAD_API_COMPATIBILITY_POLICY = {
  electronBoundary: 'contextBridge remains the only window exposure boundary.',
  legacyFacade: 'window.gamepadCli stays as a compatibility facade while renderer callers migrate to domain clients.',
  domainOwnership: 'Every legacy preload method must be assigned to exactly one target window.helm domain.',
} as const;

export const PRELOAD_API_DOMAINS = {
  app: [
    'appGetVersion',
    'appStartupReady',
    'appConfirmClose',
  ],
  sessions: [
    'sessionSetActive',
    'sessionGetActive',
    'sessionRemove',
    'sessionClose',
    'sessionSnapOut',
    'sessionSnapBack',
    'sessionRename',
    'sessionSetLocked',
    'sessionSetState',
    'sessionRequestFocusSlot',
    'sessionFocusWindow',
  ],
  terminal: [
    'terminalAttach',
    'terminalDetach',
    'ptySpawn',
    'ptyWrite',
    'ptyScrollInput',
    'ptyResize',
    'ptyMarkSwitching',
    'ptyKill',
  ],
  delivery: [
    'pipelineEnqueue',
    'pipelineDequeue',
    'pipelineGetQueue',
    'pipelineGetPosition',
    'handoverCancel',
    'handoverPending',
  ],
  config: [
    'configGetAll',
    'configGetBindings',
    'configGetCliTypes',
    'configGetChipbarActions',
    'configSetChipbarActions',
    'configSetSequenceGroup',
    'configRemoveSequenceGroup',
    'configSetBinding',
    'configRemoveBinding',
    'configCopyCliBindings',
    'configGetHapticFeedback',
    'configSetHapticFeedback',
    'configGetNotifications',
    'configSetNotifications',
    'configGetMcpConfig',
    'configSetMcpConfig',
    'configGetFleetConfig',
    'configGetFleetStatus',
    'configSetFleetConfig',
    'configGenerateMcpToken',
    'configGetEscProtectionEnabled',
    'configSetEscProtectionEnabled',
    'configGetSortPrefs',
    'configSetSortPrefs',
    'configGetPlanFilters',
    'configSetPlanFilters',
    'configGetSessionGroupPrefs',
    'configSetSessionGroupPrefs',
    'configRemoveBookmarkedDir',
    'configGetSpawnCommand',
    'configGetCliTypeEnv',
    'configGetDpadConfig',
    'configGetStickConfig',
    'configGetWorkspaceLayout',
    'configSetWorkspaceLayout',
    'configGetEditorPrefs',
    'configSetEditorPrefs',
    'configGetWorkingDirs',
  ],
  tools: [
    'toolsGetAll',
    'toolsAddCliType',
    'toolsUpdateCliType',
    'toolsRemoveCliType',
    'toolsReorderCliType',
  ],
  projects: [
    'projectList',
    'projectGet',
    'projectCreate',
    'projectUpdate',
    'projectDelete',
    'projectAddDir',
    'projectRemoveDir',
    'projectSetMainDir',
  ],
  mess: [
    'messHistory',
    'onMessAppended',
  ],
  skills: [
    'skillList',
    'skillGet',
    'skillGetStats',
    'skillSubmitFeedback',
    'skillClearReviews',
    'skillResetUseCount',
    'skillResetAllCounts',
    'skillCreate',
    'skillUpdate',
    'skillDelete',
    'skillClone',
  ],
  plans: [
    'planList',
    'planCreate',
    'planUpdate',
    'planDelete',
    'planClearCompleted',
    'planAddDep',
    'planRemoveDep',
    'planApply',
    'planComplete',
    'planReopen',
    'planSetState',
    'planStartableForDir',
    'planDoingForSession',
    'planGetAllDoingForDir',
    'planDeps',
    'planGetItem',
    'planSequenceList',
    'planSequenceCreate',
    'planSequenceUpdate',
    'planSequenceDelete',
    'planSequenceAssign',
    'planBulkAssignSequence',
    'planSequenceDeleteWithPlans',
    'planPopOut',
    'planOpenExternal',
  ],
  contexts: [
    'planContextList',
    'planContextCreate',
    'planContextUpdate',
    'planContextDelete',
    'planContextGet',
    'planContextSetPosition',
    'planContextBind',
    'planContextUnbind',
  ],
  memory: [
    'memoryList',
    'memoryGet',
    'memorySearch',
    'memoryGraph',
    'memoryGraphAll',
    'memoryExport',
    'memoryDelete',
    'memoryAttachmentList',
    'memoryAttachmentOpen',
    'memoryAttachmentDelete',
  ],
  attachments: [
    'planAttachmentList',
    'planAttachmentHasAny',
    'planAttachmentAddFile',
    'planAttachmentDelete',
    'planAttachmentOpen',
  ],
  incoming: [
    'planIncomingList',
    'planIncomingDelete',
    'planIncomingOpen',
    'planExportItem',
    'planExportDirectory',
    'planReadFile',
    'planWriteFile',
  ],
  drafts: [
    'draftCreate',
    'draftUpdate',
    'draftDelete',
    'draftList',
    'draftCount',
    'editorGetHistory',
    'editorSetHistory',
  ],
  scheduler: [
    'scheduledTaskCreate',
    'scheduledTaskList',
    'scheduledTaskGet',
    'scheduledTaskUpdate',
    'scheduledTaskRunNow',
    'scheduledTaskCancel',
    'scheduledTaskDelete',
    'scheduledTaskListHistory',
    'scheduledTaskClearHistory',
  ],
  recycleBin: [
    'recycleBinList',
    'recycleBinRestore',
    'recycleBinCommitRestore',
    'recycleBinForget',
    'recycleBinEmpty',
  ],
  runtimeGroups: [
    'runtimeGroupList',
    'runtimeGroupCreate',
    'runtimeGroupRename',
    'runtimeGroupSetCollapsed',
    'runtimeGroupAddSession',
    'runtimeGroupRemoveSession',
    'runtimeGroupCloseGroup',
    'runtimeGroupReattach',
  ],
  artifacts: [
    'artifactList',
    'artifactCounts',
    'artifactGet',
    'artifactPrepareRender',
    'artifactDelete',
    'artifactDeleteAll',
    'artifactReveal',
    'artifactExport',
    'artifactOpenExternal',
    'artifactCreateText',
    'artifactCreateWithFile',
    'artifactPickAndReadFile',
    'artifactRename',
    'artifactUpdate',
    'artifactOpenAttachment',
  ],
  peers: [
    'peerListDiscovered',
    'peerStartPairing',
    'peerStartPairingByAddress',
    'peerConfirmPairing',
    'peerCancelPairing',
    'peerList',
    'peerSetAllowList',
    'peerSetEnabled',
    'peerUnpair',
    'peerGetAudit',
    'peerFleetEnabled',
  ],
  mobile: [
    'mobileList',
    'mobileStartPairing',
    'mobileConfirmPairing',
    'mobileCancelPairing',
    'mobilePairingState',
    'mobileSetAllowList',
    'mobileSetEnabled',
    'mobileRevoke',
    'mobileApkRelease',
  ],
  patterns: [
    'toolsGetPatterns',
    'toolsAddPattern',
    'toolsUpdatePattern',
    'toolsRemovePattern',
    'patternCancelSchedule',
  ],
  telegram: [
    'telegramGetConfig',
    'telegramSetConfig',
    'telegramStart',
    'telegramStop',
    'telegramIsRunning',
    'telegramTestConnection',
  ],
  promptTemplates: [
    'promptTemplateList',
    'promptTemplateGetNode',
    'promptTemplateCreateFolder',
    'promptTemplateCreateTemplate',
    'promptTemplateUpdate',
    'promptTemplateRename',
    'promptTemplateDelete',
    'promptTemplateMove',
    'promptTemplateReorder',
  ],
  keyboard: [
    'keyboardKeyTap',
    'keyboardSendKeyCombo',
    'keyboardComboDown',
    'keyboardComboUp',
  ],
  dialog: [
    'dialogOpenFolder',
    'dialogShowOpenFile',
    'dialogShowSaveFile',
    'editorOpenExternal',
    'writeTempContent',
    'deleteTemp',
  ],
  system: [
    'systemOpenLogsFolder',
    'systemOpenHelp',
    'systemOpenExternalUrl',
  ],
  events: [
    'onPtyData',
    'onPtyExit',
    'onPtyQuestionDetected',
    'onPtyQuestionCleared',
    'onPtyActivityChange',
    'onPtyHandoff',
    'onHandoverArmed',
    'onHandoverDelivered',
    'onHandoverLost',
    'onNotificationClick',
    'onLlmNotify',
    'onFlashAttention',
    'onSessionSpawned',
    'onSessionUpdated',
    'onSnapOut',
    'onSnapBack',
    'onFocusSlot',
    'onPlanChanged',
    'onPlanIncomingImported',
    'onPlanIncomingError',
    'onPlanIncomingErrorCleared',
    'onProjectChanged',
    'onPatternScheduleCreated',
    'onPatternScheduleFired',
    'onPatternScheduleCancelled',
    'onScheduledTaskChanged',
    'onScheduledTaskHistoryChanged',
    'onRecycleBinChanged',
    'onRuntimeGroupChanged',
    'onArtifactChanged',
    'onMemoryChanged',
    'onArtifactReveal',
    'onPromptTemplateChanged',
    'onAppCloseRequest',
    'onPeerDiscovered',
    'onPeerLost',
    'onPeerIncoming',
    'onPeerSas',
    'onPeerPaired',
    'onPeerFailed',
    'onPeerConfigChanged',
    'onPeerLinkStatus',
    'onPeerAuditChanged',
    'onMobileDevicesChanged',
    'onMobilePairingState',
  ],
} as const;

export type PreloadApiDomain = keyof typeof PRELOAD_API_DOMAINS;

export function getPreloadApiDomain(methodName: string): PreloadApiDomain | undefined {
  return (Object.entries(PRELOAD_API_DOMAINS) as Array<[PreloadApiDomain, readonly string[]]>)
    .find(([, methods]) => methods.includes(methodName))?.[0];
}
