/**
 * Static list of all MCP tools exposed by Helm.
 * Extracted from session-info-guide.ts to keep that file under 100 lines.
 */

import type { McpToolSummary } from '../helm-control-service.js';
import { REQUIRED_PLAN_DESCRIPTION_SECTIONS } from './agent-plan-guide.js';

/** List of all MCP tools with names and titles (used by tests to verify tool surface). */
export function getAvailableTools(): McpToolSummary[] {
  return [
    { name: 'tool_list', title: 'List CLI Types', description: 'List CLI types configured in Helm and the configured working directories they can be spawned into.' },
    { name: 'skill_list', title: 'List Skills', description: 'List Helm skills (user-managed and system), optionally filtered by projectId or dirPath. session_info returns skills applicable to the current session project.' },
    { name: 'skill_get', title: 'Get Skill', description: 'Fetch a Helm skill by ID, or resolve by type with optional projectId/dirPath for project-scoped effective resolution.' },
    { name: 'skill_submit_feedback', title: 'Submit Skill Feedback', description: 'Rate a user skill after applying it; stores stars, summary, optional improvement, and caller CLI attribution.' },
    { name: 'skill_get_feedback', title: 'Get Skill Feedback', description: 'Read a skill\'s useCount, avgRating and every review before rewriting it.' },
    { name: 'skill_clear_reviews', title: 'Clear Skill Reviews', description: 'Discard a skill\'s reviews (use count is kept) after rewriting it.' },
    { name: 'skill_create', title: 'Create Skill', description: 'Create a Helm skill. Use allProjects=true or projectIds to control which projects receive it.' },
    { name: 'skill_update', title: 'Update Skill', description: 'Update a Helm skill. Protected skills reject AI amendments unless aiAmendable is enabled.' },
    { name: 'skill_delete', title: 'Delete Skill', description: 'Delete a user-managed Helm skill by id. System skills cannot be deleted.' },
    { name: 'plan_list', title: 'List Plans', description: "List plan items for a directory before editing or assigning work. Returned humanId values such as P-0035 are Helm plan IDs. Optional filter: 'active' (default, non-done), 'all' (incl. done), 'startable' (non-done frontier with precursors complete)." },
    { name: 'plan_summary', title: 'Plans Summary', description: "List compact plan status, canonical IDs, human-readable P-ids, sequence IDs, and dependency relationships before claiming work. Optional filter: 'active' (default, non-done), 'all' (incl. done), 'startable' (non-done frontier with precursors complete)." },
    { name: 'plan_get', title: 'Get Plan', description: 'Get full plan details before changing state, editing content, or asking about a plan, including lightweight sequenceContextMetadata when available. The id argument accepts either UUID or P-00xx humanId.' },
    { name: 'plan_create', title: 'Create Plan', description: `Create durable follow-up or question plans. Set autoImplement=true when a ready follow-up may be picked up automatically after its prerequisite is completed. Descriptions should include: ${REQUIRED_PLAN_DESCRIPTION_SECTIONS.join(', ')}.` },
    { name: 'plan_update', title: 'Update Plan', description: 'Update a plan title, description, type, autoImplement flag, and/or completionRecap flag while preserving existing context unless the edit is intentional. Set autoImplement true or false to control automatic follow-up pickup. Set completionRecap true or false to control the read-verification recap gate. The id argument accepts UUID or P-00xx humanId.' },
    { name: 'plan_delete', title: 'Delete Plan', description: 'Delete a plan item by UUID or P-00xx humanId.' },
    { name: 'plan_set_state', title: 'Set Plan State', description: 'Set plan lifecycle state by UUID or P-00xx humanId.' },
    { name: 'plan_complete', title: 'Complete Plan', description: 'Mark a coding or review plan as done by UUID or P-00xx humanId with documentation of behavior changed, files, tests/review, and remaining risk.' },
    { name: 'plan_context_list', title: 'List Effective Plan Context', description: 'List effective context refs for one plan before implementation; fetch full context just-in-time only when relevant to the current phase.' },
    { name: 'plan_nextplan_link', title: 'Link Next Plan', description: 'Link one plan as a prerequisite for another using UUIDs or P-00xx humanIds. For blocker questions, link the QUESTION plan to the original blocked plan.' },
    { name: 'plan_nextplan_unlink', title: 'Unlink Next Plan', description: 'Remove a prerequisite link between two plan items using UUIDs or P-00xx humanIds.' },
    { name: 'sequence_list', title: 'List Sequences', description: 'List sequence coordination lanes for a directory or plan, including member plan IDs and legacy sharedMemory. Prefer context_* tools for new durable memory.' },
    { name: 'sequence_get', title: 'Get Sequence', description: 'Get one sequence coordination lane by ID, including member plan IDs and legacy sharedMemory.' },
    { name: 'sequence_create', title: 'Create Sequence', description: 'Create a sequence coordination lane that plans can join. Prefer context_* tools over sharedMemory for new durable notes.' },
    { name: 'sequence_update', title: 'Update Sequence', description: 'Update sequence title, mission, sharedMemory, or order. sharedMemory is legacy; prefer context_* for new durable memory. Pass expectedUpdatedAt for mutex-style write protection.' },
    { name: 'sequence_delete', title: 'Delete Sequence', description: 'Delete a sequence and clear membership from member plans.' },
    { name: 'sequence_assign', title: 'Assign Sequence', description: 'Assign or unlink a plan from a sequence without deleting the sequence.' },
    { name: 'context_list', title: 'List Context Nodes', description: 'List project-level context nodes by projectId, including their plan and sequence bindings.' },
    { name: 'context_create', title: 'Create Context Node', description: 'Create a durable project-level context node. Bind it to a plan or sequence with context_bind when it should appear on that surface.' },
    { name: 'context_update', title: 'Update Context Node', description: 'Update context title, type, permission, content, or stored canvas position.' },
    { name: 'context_delete', title: 'Delete Context Node', description: 'Delete a context node and remove its plan and sequence bindings.' },
    { name: 'context_get', title: 'Get Context Node', description: 'Fetch a context node by ID, including full content and binding metadata.' },
    { name: 'context_set_position', title: 'Set Context Position', description: 'Persist a context card X/Y position on the planner canvas.' },
    { name: 'context_bind', title: 'Bind Context Node', description: 'Associate a context node with a plan or sequence in the same directory.' },
    { name: 'context_unbind', title: 'Unbind Context Node', description: 'Remove one plan or sequence association from a context node without deleting it.' },
    { name: 'plan_attachment_list', title: 'List Plan Attachments', description: 'List files attached to a plan by UUID or P-00xx humanId.' },
    { name: 'plan_attachment_add', title: 'Add Plan Attachment', description: 'Attach an existing file to a plan by local file path. The caller owns the source and Helm never deletes or modifies it; Helm owns the stored copy until attachment deletion.' },
    { name: 'plan_attachment_delete', title: 'Delete Plan Attachment', description: 'Delete one stored attachment from a plan by attachment ID.' },
    { name: 'plan_attachment_get', title: 'Get Plan Attachment Temp File', description: 'Copy an attachment to a Helm temp file and return the local temp path instead of inline content. Caller must delete the returned temp file after reading; Helm may reap stale temp files on startup.' },
    { name: 'directory_list', title: 'List Directories', description: 'List all directories that Helm knows about: configured folders plus directories that currently have plans or sessions. Alternate folders remain separate selectable dirPath entries while sharing projectId when they belong to the same project.' },
    { name: 'session_create', title: 'Create Session', description: 'Spawn a new CLI session in a configured working directory with a stable display name. Optional runtimeGroupId places it in a runtime group (omit to inherit the creator\'s group, "none" for project-only).' },
    { name: 'session_group_list', title: 'List Session Groups', description: 'List runtime session groups (user-created cross-directory overlay): id, name, member sessionIds, collapsed.' },
    { name: 'session_group_create', title: 'Create Session Group', description: 'Create a new empty runtime session group and return its id.' },
    { name: 'session_group_add', title: 'Add Session To Group', description: 'Add a session (by id or name) to a runtime group by id. Membership is exclusive.' },
    { name: 'session_group_remove', title: 'Remove Session From Group', description: 'Remove a session (by id or name) from whichever runtime group it is in; it stays under its project.' },
    { name: 'session_group_rename', title: 'Rename Session Group', description: 'Rename a runtime session group by id.' },
    { name: 'session_group_close', title: 'Close Session Group', description: 'Delete a runtime session group by id; member sessions fall back to directory grouping.' },
    { name: 'session_list', title: 'List Sessions', description: 'List currently known Helm sessions, optionally filtered to one working directory or project.' },
    { name: 'session_get', title: 'Get Session', description: 'Get a session by ID or exact display name.' },
    { name: 'session_send_text', title: 'Send Text To Session', description: 'Send text to a running session PTY, with optional reply routing through HELM_MSG metadata.' },
    { name: 'session_clear', title: 'Clear Session Context', description: 'Clear a target session (sessionId required) by delivering its configured helmActions.clear command (fallback: clearCommand, then "/clear"), then optionally relay a note-to-future-self. Large notes are offloaded to a temp file.' },
    { name: 'session_compact', title: 'Compact Session Context', description: 'Compact a target session (sessionId required) via its configured helmActions.compact command; the optional instruction fills the $instruction placeholder. Pass handover to have a note-to-your-post-compaction-self pasted back once the session falls quiet. Errors if unconfigured for that CLI.' },
    { name: 'session_export', title: 'Export Session To File', description: 'Export a target session (sessionId required) to a caller-supplied file path via its configured helmActions.export command ($path placeholder). Harvest an old session\'s knowledge without paying to reactivate it. Errors if unconfigured.' },
    { name: 'session_read_terminal', title: 'Read Session Terminal', description: 'Read the recent terminal tail for any known session by ID or exact display name, with raw, stripped, or both output modes.' },
    { name: 'session_plan_claim', title: 'Claim Plan', description: 'Claim a plan for this session: records ownership, auto-transitions ready→coding, and shows the plan badge on the session row.' },
    { name: 'session_set_aiagent_state', title: 'Set Session AIAGENT State', description: 'Update the durable AIAGENT phase for a session. Valid states: planning, implementing, completed, idle.' },
    { name: 'session_set_locked', title: 'Set Session Lock', description: 'Set or clear a durable lock that prevents deliberate session closure.' },
    { name: 'session_set_loop_driving', title: 'Set Loop Driving', description: 'G8 opt-in: allow the Stop hook to auto-continue this session into ready, auto-implement follow-ups of plans it completes (cap 5, then it stops and flashes). OFF by default — only enable with explicit user authorization; a genuine user prompt or enabled:false ends the chain.' },
    { name: 'session_rename', title: 'Rename Session', description: 'Rename a Helm session by ID or name. Also updates the Telegram topic name.' },
    { name: 'session_close', title: 'Close Session', description: 'Close a Helm session and stop its PTY.' },
    { name: 'session_info', title: 'Get Session Info', description: 'Retrieve session identity, startup guidance, the project knowledge model, and durable_memory contract: project scope, compaction/restart/session-death durability, recycle-bin continuity, permanent purge on forget/empty/expiry, graphDepth/cycle breadcrumbs, regex search, and non-searchable attachments.' },
    { name: 'memory_list', title: 'List Memories', description: 'List durable memories for the project resolved from the authenticated caller session; attachment content is not included.' },
    { name: 'memory_get', title: 'Get Memory', description: 'Get one project memory resolved from the authenticated caller session with optional graphDepth traversal, breadcrumbs, and cycle-safe markers.' },
    { name: 'memory_create', title: 'Create Memory', description: 'Create a durable memory in the project resolved from the authenticated caller session.' },
    { name: 'memory_update', title: 'Update Memory', description: 'Update a project memory resolved from the authenticated caller session with optional optimistic concurrency protection.' },
    { name: 'memory_delete', title: 'Delete Memory', description: 'Delete a project memory resolved from the authenticated caller session and reroute valid project graph edges.' },
    { name: 'memory_search', title: 'Search Memories', description: 'Search project memory tldr/content resolved from the authenticated caller session literally or with regex=true, optionally expanding matching roots by graphDepth.' },
    { name: 'memory_graph', title: 'Traverse Memory Graph', description: 'Traverse the project memory graph resolved from the authenticated caller session with graphDepth, breadcrumbs, and cycle-safe markers.' },
    { name: 'memory_export', title: 'Export Memories', description: 'Export project memories resolved from the authenticated caller session as pure Markdown or lossless JSON with optional rootId/graphDepth; attachment bytes and storage paths are excluded.' },
    { name: 'memory_link', title: 'Link Memories', description: 'Create a directed edge between two project memories resolved from the authenticated caller session.' },
    { name: 'memory_unlink', title: 'Unlink Memories', description: 'Remove a directed edge between two project memories resolved from the authenticated caller session.' },
    { name: 'memory_attachment_add', title: 'Add Memory Attachment', description: 'Attach an absolute source file to a project memory resolved from the authenticated caller session and return metadata only.' },
    { name: 'memory_attachment_list', title: 'List Memory Attachments', description: 'List metadata for attachments on a project memory resolved from the authenticated caller session; attachment content is not searchable.' },
    { name: 'memory_attachment_get', title: 'Get Memory Attachment', description: 'Copy a project memory attachment resolved from the authenticated caller session to a safe tempPath and return metadata, never inline bytes.' },
    { name: 'memory_attachment_delete', title: 'Delete Memory Attachment', description: 'Delete an attachment from a project memory resolved from the authenticated caller session.' },
    { name: 'mess_post', title: 'Post Mess', description: 'Store a bounded local project coordination message for the authenticated caller.' },
    { name: 'mess_check', title: 'Check Mess', description: 'Read the authenticated caller\'s bounded unread project Mess delta.' },
    { name: 'mess_history', title: 'Read Mess History', description: 'Read the last N project Mess notes grouped by date, without advancing the caller cursor.' },
    { name: 'mess_search', title: 'Search Mess', description: 'Find project Mess notes by literal text, with optional surrounding context.' },
    { name: 'notify_user', title: 'Notify User', description: 'Send an LLM-directed notification to a target session with smart delivery routing when work completes, you are blocked for user input, or an error stops progress.' },
    { name: 'get_app_visibility', title: 'Get App Visibility', description: 'Return app visibility, screen lock state, and activeSessionId for notification routing.' },
    { name: 'telegram_status', title: 'Telegram Status', description: 'Report whether Telegram is enabled, configured, running, and available for urgent mobile-friendly user communication.' },
    { name: 'chat_send', title: 'Send Chat', description: 'Send concise mobile-friendly text to the user over the session\'s bound chat surfaces (a paired phone over BLE; Telegram if configured). Replies go to YOUR OWN session topic automatically; sessionId is an optional override. Resolving by name is not supported. Lines must be short; do not send large wide logs, tables, or code blocks.' },
    { name: 'telegram_chat', title: 'Send Telegram Chat', description: 'Alias of chat_send. Send concise mobile-friendly text to the user via Telegram. Replies go to YOUR OWN session topic automatically; sessionId is an optional override. Resolving by name is not supported. Lines must be short; do not send large wide logs, tables, or code blocks.' },
    { name: 'telegram_send_voice', title: 'Send Telegram Voice Reply', description: 'Helm synthesizes speech and sends it as a native Telegram voice message to YOUR session topic. Text is the default reply channel — only send voice when the user explicitly requests a voice reply. Only available when piper+ffmpeg are configured.' },
    { name: 'telegram_channel_close', title: 'Close Telegram Channel', description: 'Close one MCP Telegram communication channel without deleting unrelated session topics.' },
    { name: 'scheduler_create', title: 'Create Scheduler Entry', description: 'Create a scheduled task. Direct tasks can use targetSession:"caller" as a self-timer for the creating Helm session.' },
    { name: 'scheduler_list', title: 'List Scheduler Entries', description: 'List all scheduled tasks.' },
    { name: 'scheduler_get', title: 'Get Scheduler Entry', description: 'Get a scheduled task by ID.' },
    { name: 'scheduler_update', title: 'Update Scheduler Entry', description: 'Update a pending scheduled task. Only pending tasks can be updated.' },
    { name: 'scheduler_cancel', title: 'Cancel Scheduler Entry', description: 'Cancel a pending scheduled task.' },
    { name: 'scheduler_delete', title: 'Delete Scheduler Entry', description: 'Delete a scheduled task and cancel its pending run.' },
  ];
}
